### ISSUE TITLE
Error Body along with Exception

### ISSUE THREAD

**Issue by livingmyway** [smilecs/ketro#12]
**Description**
When the API call fails for one of the `40XX` client errors, the `onException` method gets called where the `ApiErrorHandler()` class returns an `Exception` with a message property but not the error body. The Exception class has a property `message` that can be overriden in the custom error handler class and a message can be sent back to the observer as part of the exception. As the Exception class doesn't have a `ResponseBody` property, a `responseBody` cannot be sent with the exception. The responseBody can be converted to a string using the `toStirng()` method and sent as a message but it makes it very hard for the observer to convert it back to a ResponseBody. It's nice to have the library take care of this as the boiler plate is nicely setup in the library already.

**Use case**
APIs return response bodies of a specific model to the client so that the client can convert the `responseBody` to that model object which can then be used to control views.

**Expected Result**
The `onSuccess` method should get called for success response that doesn't have a body.

**Notes for dev**
Modify the `ApiErrorHandler` to return something with exception and also includes a property `ResponseBody`. Using this, the custom error handler class can send `response.errorBody` as part of the exception that the observer can use as below:
```bash
override fun onException(exception: Exception) {
                val errorBody = exception.errorBody
    // converter is a function to convert errorBody to errorDetails
               val errorDetails = converter.convert(errorBody)
               textView.text = errorDetails.errors[0].message
            }
```
ErrorDetails Model:
```bash
class ErrorDetails : Serializable {
   var errors: List<Error>? = null

    inner class Error : Serializable {
        var message: String? = null
        var price: Double = 0.0
        var tax: Double = 0.0
    }
}
```

**Example `errorBody` returned by the api**
`Body: {"errors":[{"message":"Balance too low","price":10,"tax":3}]}`

**Comment by smilecs** [comment]
fixed in #16
