### ISSUE TITLE
App is crashed when no internet connection while api calling

### ISSUE THREAD

**Issue by chichi289** [smilecs/ketro#32]
**Describe the bug**
App is crashed when you disable your internet connection and call api

**To Reproduce**
1. Install sample app from ketro github repository 
2. Disable internet connection in device 
3. Enter any GitHub user name and click on search button to call api
4. App is crashed

**Expected behavior**
It should show message to user for no connection

**Smartphone:**
 - Device: Le X526
 - OS: Android 6.0.1

**Additional context**
How can we handle this scenario by using ketro?

**Comment by smilecs** [comment]
@chichi289 a network call with retrofit throws an IOException, and ketro sample app using coroutines, should have a handler with it's scope. I will push an update to the sample app to address this scenario thank you.

**Comment by smilecs** [comment]
fixed in #33
